In [2]:
import numpy as np

In [6]:
np_1 = np.array([1, 2, 3, 4, 'salom', 'ali', 1.0, True])

print(np_1)

['1' '2' '3' '4' 'salom' 'ali' '1.0' 'True']


In [9]:
np_2 = np.array([1, 2, 3, 4, 10.5])

print(np_2)

[ 1.   2.   3.   4.  10.5]


In [10]:
list_2 = [1, 2, 3, 4, 5]

list_2 = [i * 2 for i in list_2]

print(list_2)

[2, 4, 6, 8, 10]


In [11]:
np_2 = np.array([1, 2, 3, 4, 5])

np_2 = np_2 * 2

print(np_2)

[ 2  4  6  8 10]


In [12]:
list_2 = [1, 2, 3, 4, 5] * 2

print(list_2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [16]:
list_3 = list(range(1000000))

np_3 = np.array(list_3)

In [18]:
% time for i in range(10):[i * 2 for i in list_3]

CPU times: total: 328 ms
Wall time: 1.19 s


In [20]:
% time for i in range(10): np_3 * 2

CPU times: total: 15.6 ms
Wall time: 22 ms


In [21]:
np_1 = np.array([1, 2, 3, 4, 5])

print(np_1)

[1 2 3 4 5]


In [22]:
print(type(np_1))

<class 'numpy.ndarray'>


In [24]:
np_2 = np.asarray([1, 2, 3, 4, 5])

print(np_2)

[1 2 3 4 5]


In [25]:
type(np_2)

numpy.ndarray

In [26]:
np_3 = np.arange(100)

print(np_3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [29]:
np_4 = np.ones(3)

print(np_4)

[1. 1. 1.]


In [30]:
np_4 = np.ones((3, 3))

print(np_4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
np_4 = np.ones((3, 3, 3))

print(np_4)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [32]:
np_4 = np.ones((3, 3, 3, 2))

print(np_4)

[[[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]]


In [36]:
np_5 = np.ones_like([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

print(np_5)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [42]:
np_6 = np.zeros((2, 3, 4))

print(np_6)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [39]:
np_6 = np.zeros_like([1, 2, 3, 4, 5, 34])

print(np_6)

[0 0 0 0 0 0]


In [40]:
np_7 = np.full((3, 4), fill_value=5)

print(np_7)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [43]:
np_8 = np.full_like(np_6, fill_value=5)

print(np_8)

[[[5. 5. 5. 5.]
  [5. 5. 5. 5.]
  [5. 5. 5. 5.]]

 [[5. 5. 5. 5.]
  [5. 5. 5. 5.]
  [5. 5. 5. 5.]]]


In [44]:
np_9 = np.empty((3, 4))

print(np_9)

[[7.24386048e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [6.89903272e-310 3.30525971e+179 9.30590749e+165 5.64832338e-038]
 [9.57819973e+169 6.87158884e+169 6.94235637e+169 3.63071191e+179]]


In [47]:
np_10 = np.eye(3, 4)

print(np_10)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [48]:
np_10 = np.eye(3)

print(np_10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
np_11 = np.identity(5)

print(np_11)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [50]:
np_12 = np.random.rand(3)

print(np_12)

[0.96597136 0.59792283 0.18405283]


In [51]:
np_12 = np.random.rand(3, 3)

print(np_12)

[[0.59132842 0.66821488 0.03207081]
 [0.0218795  0.11679976 0.93952631]
 [0.66787275 0.32655072 0.82511252]]


In [53]:
np_13 = np.random.randn(3)

print(np_13)

[-0.42310086 -0.46460839  1.59553274]


In [54]:
np_13 = np.random.randn(3, 2)

print(np_13)

[[ 1.28392994  0.27481225]
 [ 0.23992626  1.0855219 ]
 [-0.41323788  0.36135157]]


In [55]:
np_13 = np.random.randint(0, 10)

print(np_13)

9


In [56]:
np_13 = np.random.randint(0, 10, size=(10))

print(np_13)

[9 6 5 6 4 0 2 1 2 3]


In [59]:
np_13 = np.random.randint(0, 10, size=(10, 12))

print(np_13)

[[6 1 1 3 4 8 9 9 7 0 6 2]
 [4 5 1 6 2 7 3 9 6 4 0 1]
 [1 2 6 7 2 4 7 1 1 9 3 4]
 [1 5 1 4 7 3 2 9 5 3 1 5]
 [7 8 7 4 9 8 2 5 8 6 6 1]
 [2 2 1 6 1 7 0 3 3 7 3 3]
 [1 2 3 6 3 9 8 8 3 6 2 2]
 [4 3 2 5 9 7 3 7 2 4 5 6]
 [7 7 5 7 7 1 7 1 9 5 9 2]
 [7 3 0 9 8 3 6 3 7 2 7 0]]
