In [1]:
import numpy as np

* ##### np.array
* ##### np.asarray
* ##### np.arange
* ##### np.ones
* ##### np.ones_like
* ##### np.zeros
* ##### np.zeros_like
* ##### np.full
* ##### np.full_like
* ##### np.empty
* ##### np.empty_like
* ##### np.eye
* ##### np.identity
* ##### np.random randint, rand, randn

# Numpy attributes
#### * dtype
#### * size
#### * shape
#### * ndim

In [2]:
a = np.ones((5, 6, 4))

print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [3]:
a.shape

(5, 6, 4)

In [4]:
a.size

120

In [5]:
a.dtype

dtype('float64')

In [6]:
a.ndim

3

In [7]:
a.nbytes

960

In [8]:
a = np.ones((5, 6, 4), dtype=np.uint8)

print(a)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [9]:
a.nbytes

120

In [11]:
np_1 = np.array([1, 2, 3, 4], np.int8)

print(np_1)

[1 2 3 4]


In [12]:
np_1 = np.array([128, 2, 3, 4], np.int8)

print(np_1)

[-128    2    3    4]


In [14]:
np_1 = np.array([256, 2, 3, 4], np.int8)

print(np_1)

[0 2 3 4]


In [15]:
np_1 = np.array([356, 2, 3, 4], np.int8)

print(np_1)

[100   2   3   4]


In [16]:
np_2 = np.array([-1, 2, 3, 4], np.uint8)

print(np_2)

[255   2   3   4]


In [17]:
np_2 = np.array([-10, 2, 3, 4], np.uint8)

print(np_2)

[246   2   3   4]


In [18]:
np_3 = np.arange(10)
print(np_3)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
print(np_3.shape)

(10,)


In [20]:
np_3.ndim

1

In [21]:
np_3.size

10

In [22]:
np_4 = np_3.reshape(2, 5)

print(np_4)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
np_3 = np.arange(27)
print(np_3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [24]:
np_4 = np_3.reshape(3, 3, 3)

print(np_4)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [25]:
np_1d = np.array([1, 2, 3, 4])
np_2d = np.arange(12).reshape(3, 4)
np_3d = np.arange(18).reshape(3, 2, 3)

In [26]:
print(np_1d)

[1 2 3 4]


In [27]:
print(np_1d[1])

2


In [28]:
print(np_1d[1:3])

[2 3]


In [29]:
print(np_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
print(np_2d[1, 1])

5


In [31]:
print(np_2d[1:, 2:])

[[ 6  7]
 [10 11]]


In [32]:
print(np_3d)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [33]:
print(np_3d[1, 1, 2])

11


In [35]:
print(np_3d[2, :, 1:])

[[13 14]
 [16 17]]


In [36]:
np_4 = np_3d[1:, :, 1]

In [37]:
print(np_4)

[[ 7 10]
 [13 16]]


In [38]:
print(np_3d)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [39]:
np_3d[1, 0, 1] = 100

print(np_3d)

[[[  0   1   2]
  [  3   4   5]]

 [[  6 100   8]
  [  9  10  11]]

 [[ 12  13  14]
  [ 15  16  17]]]


In [40]:
print(np_4)

[[100  10]
 [ 13  16]]


In [41]:
ismlar = np.array(['Sodiq', "Adbulhay", 'Dilmurod', "Farrux", "Ibratillo"])
pullari = np.random.randint(100000, 1000000, size=(5, 4))

In [42]:
print(ismlar)

['Sodiq' 'Adbulhay' 'Dilmurod' 'Farrux' 'Ibratillo']


In [43]:
print(pullari)

[[439790 940124 946589 367856]
 [817869 914874 141641 376044]
 [411691 266627 508521 952503]
 [775405 772582 540639 134485]
 [156209 872786 538048 939835]]


In [45]:
print(pullari[ismlar == 'Sodiq'])

[[439790 940124 946589 367856]]


In [47]:
print(ismlar == 'Sodiq')

[ True False False False False]


In [48]:
ismlar = np.array(['Sodiq', "Adbulhay", 'Sodiq', "Farrux", "Sodiq"])
pullari = np.random.randint(100000, 1000000, size=(5, 4))

In [49]:
print(ismlar)

['Sodiq' 'Adbulhay' 'Sodiq' 'Farrux' 'Sodiq']


In [50]:
print(pullari)

[[561873 729869 711459 380508]
 [349132 548920 429978 287154]
 [502394 403801 109954 154878]
 [233832 697464 217773 663059]
 [515174 858913 882386 640756]]


In [51]:
print(pullari[ismlar == 'Sodiq'])

[[561873 729869 711459 380508]
 [502394 403801 109954 154878]
 [515174 858913 882386 640756]]


In [52]:
print(ismlar == 'Sodiq')

[ True False  True False  True]


In [55]:
print(pullari[(ismlar == 'Sodiq') | (ismlar == 'Adbulhay')])

[[561873 729869 711459 380508]
 [349132 548920 429978 287154]
 [502394 403801 109954 154878]
 [515174 858913 882386 640756]]


In [56]:
print((ismlar == 'Sodiq') | (ismlar == 'Adbulhay'))

[ True  True  True False  True]


In [57]:
print(pullari[(ismlar == 'Sodiq') | (ismlar == 'Adbulhay'), 2])

[711459 429978 109954 882386]


In [58]:
print(pullari[pullari > 200000])

[561873 729869 711459 380508 349132 548920 429978 287154 502394 403801
 233832 697464 217773 663059 515174 858913 882386 640756]


In [59]:
print(pullari[pullari < 200000])

[109954 154878]


In [60]:
np_5 = np.arange(1, 9)

print(np_5)

[1 2 3 4 5 6 7 8]


In [61]:
print(np_5 * 5)

[ 5 10 15 20 25 30 35 40]


In [62]:
print(np_5 / 5)

[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6]


In [63]:
print(np_5 - 5)

[-4 -3 -2 -1  0  1  2  3]


In [64]:
print(np_5 + 5)

[ 6  7  8  9 10 11 12 13]


In [65]:
print(np_5 % 5)

[1 2 3 4 0 1 2 3]


In [66]:
print(np_5 // 5)

[0 0 0 0 1 1 1 1]


In [67]:
print(np_5 == 5)

[False False False False  True False False False]


In [68]:
print(np_5 < 5)

[ True  True  True  True False False False False]


In [69]:
print(np_5 > 5)

[False False False False False  True  True  True]


In [70]:
print(np_5 ** 2)

[ 1  4  9 16 25 36 49 64]


In [71]:
np_6 = np.array([
    [1, 2],
    [3, 4]
])

print(np_6)

[[1 2]
 [3 4]]


In [72]:
print(np_6 - 1)

[[0 1]
 [2 3]]


In [74]:
np_6 = np.array([
    [1, 2],
    [3, 4]
])

np_7 = np.array([
    [5, 6],
    [7, 8]
])

print(np_6 - np_7)

[[-4 -4]
 [-4 -4]]


In [75]:
print(np_6 + np_7)

[[ 6  8]
 [10 12]]


In [76]:
print(np_6 * np_7)

[[ 5 12]
 [21 32]]


In [77]:
print(np_6 / np_7)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [78]:
np_8 = np.array([1, 2])

print(np_6 - np_8)

[[0 0]
 [2 2]]


In [80]:
np_10 = np.arange(12).reshape(3, 4)

print(np_10)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [81]:
print(np_10.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [83]:
print(np_10.swapaxes(0, 1))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [85]:
np_11 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [87]:
print(np.square(np_11))

[  1   4   9  16  25  36  49  64  81 100]


In [88]:
print(np.sqrt(np_11))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [89]:
print(np.exp(np_11))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [92]:
print(np.sign(np.array([-1, 2, 3, -3, 4])))

[-1  1  1 -1  1]


In [93]:
print(np.sign(np.array([-1, 2, 3, -3, 4, 0])))

[-1  1  1 -1  1  0]


In [94]:
print(np.sign(np.array([-1, 2, 300000, -3, 4], dtype=np.int8)))

[-1  1 -1 -1  1]


In [96]:
np_12 = np.arange(1, 6)
np_13 = np.arange(6, 11)

In [97]:
print(np_12 + np_12)

[ 2  4  6  8 10]


In [99]:
print(np.add(np_12, np_13))

[ 7  9 11 13 15]


In [101]:
np_12 = np.array([23, 12, 1, 13])
np_13 = np.array([3, 45, 14, 4])
print(np.maximum(np_12, np_13))

[23 45 14 13]


In [103]:
np_12 = np.arange(1, 6)
np_13 = np.arange(6, 11)

print(np.power(np_13, np_12))

[     6     49    512   6561 100000]


In [104]:
np_12 = np.array([23, 12, 1, 13])
np_13 = np.array([3, 45, 14, 4])
print(np.lcm(np_12, np_13))

[ 69 180  14  52]


In [105]:
print(np.gcd(np_12, np_13))

[1 3 1 1]
