In [1]:
import numpy as np

In [4]:
np_1 = np.array([1, 2, 3, 4])
np_2 = np.array([3, 4, 5, 2])

print(np.dot(np_1, np_2))

34


In [5]:
print(np_1 * np_2)

[ 3  8 15  8]


In [9]:
np_1 = np.array([1, 2, 3, 4]).reshape(2, 2)
np_2 = np.array([3, 4, 5, 2]).reshape(2, 2)

print(np_1, '\n')
print(np_2)

[[1 2]
 [3 4]] 

[[3 4]
 [5 2]]


In [10]:
print(np.dot(np_1, np_2))

[[13  8]
 [29 20]]


In [15]:
np_1 = np.array([1, 2])
np_2 = np.array([3, 4, 5, 2]).reshape(2, 2)

print(np.dot(np_1, np_2))

[13  8]


In [20]:
np_1 = np.array([1, 2]).reshape(2, 1)
np_2 = np.array([3, 4, 5, 2]).reshape(2, 2)

print(np.dot(np_2, np_1))

[[11]
 [ 9]]


In [26]:
np_1 = np.arange(1, 28).reshape(3, 3, 3)
np_2 = np.arange(28, 55).reshape(3, 3, 3)

print(np.matmul(np_1, np_2))

[[[ 192  198  204]
  [ 471  486  501]
  [ 750  774  798]]

 [[1326 1359 1392]
  [1686 1728 1770]
  [2046 2097 2148]]

 [[2946 3006 3066]
  [3387 3456 3525]
  [3828 3906 3984]]]


In [27]:
print(np_1 @ np_2)

[[[ 192  198  204]
  [ 471  486  501]
  [ 750  774  798]]

 [[1326 1359 1392]
  [1686 1728 1770]
  [2046 2097 2148]]

 [[2946 3006 3066]
  [3387 3456 3525]
  [3828 3906 3984]]]


In [29]:
np_3 = np.array([1, 2, 3, 4])
np_4 = np.array([3, 4, 5, 2])

print(np.matmul(np_3, np_4))
print(np_3 @ np_4)

34
34


In [30]:
np_3 = np.array([1, 2, 3, 4]).reshape(2, 2)
np_4 = np.array([3, 4, 5, 2]).reshape(2, 2)

print(np.matmul(np_3, np_4))
print(np_3 @ np_4)

[[13  8]
 [29 20]]
[[13  8]
 [29 20]]


In [31]:
print(np_3 > np_4)

[[False False]
 [False  True]]


In [32]:
print(np.greater(np_3, np_4))

[[False False]
 [False  True]]


In [33]:
print(np.greater_equal(np_3, np_4))

[[False False]
 [False  True]]


In [34]:
np_5 = np.array([True, False, True, False])
np_6 = np.array([False, False, True, True])

print(np_5 & np_6)

[False False  True False]


In [35]:
print(np_5 | np_6)

[ True False  True  True]


In [36]:
print(np_5 ^ np_6)

[ True False False  True]


In [39]:
print(~ np_5)

[False  True False  True]


In [40]:
np_7 = np.array([1, 2, 3, 4]).reshape(2, 2)
np_8 = np.array([3, 4, 5, 2]).reshape(2, 2)

print(np_7 & np_8)

[[1 0]
 [1 0]]


In [41]:
print(np_7 | np_8)

[[3 6]
 [7 6]]


In [42]:
print(np_7 ^ np_8)

[[2 6]
 [6 6]]


In [43]:
print(~ np_7)

[[-2 -3]
 [-4 -5]]


In [44]:
np_9 = np.array([1, 2], dtype=np.uint8)

print(~ np_9)

[254 253]


In [45]:
print(np_9 << 2)

[4 8]


In [46]:
np_10 = np.array([255, 254], dtype=np.uint8)

print(np_10)

[255 254]


In [48]:
print(np_10 << 2)

[252 248]


In [49]:
print(np_10 >> 2)

[63 63]


In [50]:
np_11 = np.array([1, -100], dtype=np.int8)

print(np_11)

[   1 -100]


In [51]:
print(np_11 << 7)

[-128    0]


In [54]:
print(np_11 >> 3)

[  0 -13]


In [55]:
print(np.right_shift(np_11, 3))

[  0 -13]


In [56]:
print(np.left_shift(np_11, 3))

[  8 -32]


# Where condition

In [57]:
np_12 = np.array([1, 2, 3, 4])
np_13 = np.array([5, 6, 7, 8])

print(np_12)
print(np_13)

[1 2 3 4]
[5 6 7 8]


In [60]:
print(np.where(np_12 > np_13, np_12, np_13))

[5 6 7 8]


In [61]:
print(np.where(np_12 > np_13, np_13, np_12))

[1 2 3 4]


In [62]:
np_12 = np.array([1, 5, 4, 9])
np_13 = np.array([5, 2, 7, 8])

print(np.where(np_12 > np_13, np_12, np_13))

[5 5 7 9]


In [64]:
np_14 = np.array(['Husan', "Hasan", "Salom", "Salom"])
np_15 = np.array(['TTT', "TTT", "HHH", "HHH"])

print(np.where(np_12 > np_13, np_14, np_15))

['TTT' 'Hasan' 'HHH' 'Salom']


In [65]:
np_14 = np.array(['Husan', "Hasan", "Salom", "Salom"])
np_15 = np.array(['TTT', "TTT", "HHH", "HHH"])

print(np.where(np_12 > np_13, np_14, np_15))

['TTT' 'Hasan' 'HHH' 'Salom']


In [66]:
print(np.where(5 > 4, np_14, np_15))

['Husan' 'Hasan' 'Salom' 'Salom']


In [69]:
print(np_14 > np_15)

[False False  True  True]


In [70]:
print(np.where(np_14 > np_15, np_14, np_15))

['TTT' 'TTT' 'Salom' 'Salom']


In [71]:
print(np.where(np_14 > np_15, 1, 0))

[0 0 1 1]


In [72]:
print(np.where(np_14 > np_15))

(array([2, 3], dtype=int64),)
