In [1]:
import numpy as np

In [2]:
np_1 = np.array([1, 2, 3, 4]).reshape(2, 2)

print(np_1)

[[1 2]
 [3 4]]


In [3]:
print(np_1 + 5)

[[6 7]
 [8 9]]


In [4]:
np_2 = np.random.randint(1, 9, size=(10, 10))

print(np_2)

[[7 3 5 7 3 3 5 4 6 2]
 [3 2 8 6 7 7 2 5 7 6]
 [7 8 2 5 8 3 5 5 3 8]
 [1 1 6 4 8 5 6 1 8 1]
 [8 8 3 6 7 6 7 2 4 8]
 [5 8 4 4 7 1 2 5 8 2]
 [6 5 2 7 2 6 4 4 5 3]
 [7 1 2 5 8 2 3 7 8 8]
 [8 1 8 4 1 7 4 5 3 7]
 [3 1 3 3 3 3 5 2 6 7]]


In [5]:
np_2[2:-2, 2:-2] = 0

print(np_2)

[[7 3 5 7 3 3 5 4 6 2]
 [3 2 8 6 7 7 2 5 7 6]
 [7 8 0 0 0 0 0 0 3 8]
 [1 1 0 0 0 0 0 0 8 1]
 [8 8 0 0 0 0 0 0 4 8]
 [5 8 0 0 0 0 0 0 8 2]
 [6 5 0 0 0 0 0 0 5 3]
 [7 1 0 0 0 0 0 0 8 8]
 [8 1 8 4 1 7 4 5 3 7]
 [3 1 3 3 3 3 5 2 6 7]]


# Statistik funksiyalar

In [6]:
np_3 = np.random.randint(1, 4, size=(5, 5))

print(np_3)

[[1 2 1 2 3]
 [3 1 2 2 2]
 [2 3 2 3 3]
 [1 2 2 1 2]
 [2 2 2 2 1]]


In [7]:
np.sum(np_3)

49

In [8]:
np_3.sum()

49

In [9]:
print(np.sum(np_3, axis=0))

[ 9 10  9 10 11]


In [10]:
print(np.sum(np_3, axis=1))

[ 9 10 13  8  9]


In [11]:
np_3.ndim

2

In [12]:
np_4 = np.random.randint(1, 4, size=(4, 4, 4))

print(np_4)

[[[2 3 2 2]
  [3 2 3 1]
  [3 3 1 2]
  [2 2 3 1]]

 [[3 2 2 2]
  [2 1 1 3]
  [3 3 1 1]
  [1 3 2 1]]

 [[2 2 1 3]
  [3 2 3 2]
  [2 2 3 1]
  [3 2 2 1]]

 [[1 3 1 1]
  [3 1 1 2]
  [3 2 2 1]
  [1 2 3 1]]]


In [13]:
np_4.ndim

3

In [14]:
print(np.sum(np_4))

128


In [15]:
print(np.sum(np_4, axis=0))

[[ 8 10  6  8]
 [11  6  8  8]
 [11 10  7  5]
 [ 7  9 10  4]]


In [18]:
print(np.sum(np_4, axis=1))

[[10 10  9  6]
 [ 9  9  6  7]
 [10  8  9  7]
 [ 8  8  7  5]]


In [19]:
print(np.sum(np_4, axis=2))

[[ 9  9  9  8]
 [ 9  7  8  7]
 [ 8 10  8  8]
 [ 6  7  8  7]]


In [21]:
print(np_4)

[[[2 3 2 2]
  [3 2 3 1]
  [3 3 1 2]
  [2 2 3 1]]

 [[3 2 2 2]
  [2 1 1 3]
  [3 3 1 1]
  [1 3 2 1]]

 [[2 2 1 3]
  [3 2 3 2]
  [2 2 3 1]
  [3 2 2 1]]

 [[1 3 1 1]
  [3 1 1 2]
  [3 2 2 1]
  [1 2 3 1]]]


In [20]:
np.mean(np_4)

2.0

In [22]:
print(np.mean(np_4, axis=0))

[[2.   2.5  1.5  2.  ]
 [2.75 1.5  2.   2.  ]
 [2.75 2.5  1.75 1.25]
 [1.75 2.25 2.5  1.  ]]


In [23]:
print(np.mean(np_4, axis=1))

[[2.5  2.5  2.25 1.5 ]
 [2.25 2.25 1.5  1.75]
 [2.5  2.   2.25 1.75]
 [2.   2.   1.75 1.25]]


In [24]:
print(np.mean(np_4, axis=2))

[[2.25 2.25 2.25 2.  ]
 [2.25 1.75 2.   1.75]
 [2.   2.5  2.   2.  ]
 [1.5  1.75 2.   1.75]]


In [25]:
print(np_4)

[[[2 3 2 2]
  [3 2 3 1]
  [3 3 1 2]
  [2 2 3 1]]

 [[3 2 2 2]
  [2 1 1 3]
  [3 3 1 1]
  [1 3 2 1]]

 [[2 2 1 3]
  [3 2 3 2]
  [2 2 3 1]
  [3 2 2 1]]

 [[1 3 1 1]
  [3 1 1 2]
  [3 2 2 1]
  [1 2 3 1]]]


In [26]:
print(np.cumsum(np_4))

[  2   5   7   9  12  14  17  18  21  24  25  27  29  31  34  35  38  40
  42  44  46  47  48  51  54  57  58  59  60  63  65  66  68  70  71  74
  77  79  82  84  86  88  91  92  95  97  99 100 101 104 105 106 109 110
 111 113 116 118 120 121 122 124 127 128]


In [27]:
print(np.cumsum(np_4, axis=0))

[[[ 2  3  2  2]
  [ 3  2  3  1]
  [ 3  3  1  2]
  [ 2  2  3  1]]

 [[ 5  5  4  4]
  [ 5  3  4  4]
  [ 6  6  2  3]
  [ 3  5  5  2]]

 [[ 7  7  5  7]
  [ 8  5  7  6]
  [ 8  8  5  4]
  [ 6  7  7  3]]

 [[ 8 10  6  8]
  [11  6  8  8]
  [11 10  7  5]
  [ 7  9 10  4]]]


In [30]:
print(np.cumsum(np_4, axis=1))

[[[ 2  3  2  2]
  [ 5  5  5  3]
  [ 8  8  6  5]
  [10 10  9  6]]

 [[ 3  2  2  2]
  [ 5  3  3  5]
  [ 8  6  4  6]
  [ 9  9  6  7]]

 [[ 2  2  1  3]
  [ 5  4  4  5]
  [ 7  6  7  6]
  [10  8  9  7]]

 [[ 1  3  1  1]
  [ 4  4  2  3]
  [ 7  6  4  4]
  [ 8  8  7  5]]]


In [31]:
print(np.min(np_4))

1


In [32]:
print(np.min(np_4, axis=0))

[[1 2 1 1]
 [2 1 1 1]
 [2 2 1 1]
 [1 2 2 1]]


In [33]:
print(np.min(np_4, axis=1))

[[2 2 1 1]
 [1 1 1 1]
 [2 2 1 1]
 [1 1 1 1]]


In [34]:
print(np.min(np_4, axis=2))

[[2 1 1 1]
 [2 1 1 1]
 [1 2 1 1]
 [1 1 1 1]]


# Sortlash

In [39]:
print(np_4)

[[[2 3 2 2]
  [3 2 3 1]
  [3 3 1 2]
  [2 2 3 1]]

 [[3 2 2 2]
  [2 1 1 3]
  [3 3 1 1]
  [1 3 2 1]]

 [[2 2 1 3]
  [3 2 3 2]
  [2 2 3 1]
  [3 2 2 1]]

 [[1 3 1 1]
  [3 1 1 2]
  [3 2 2 1]
  [1 2 3 1]]]


In [40]:
print(np.sort(np_4))

[[[2 2 2 3]
  [1 2 3 3]
  [1 2 3 3]
  [1 2 2 3]]

 [[2 2 2 3]
  [1 1 2 3]
  [1 1 3 3]
  [1 1 2 3]]

 [[1 2 2 3]
  [2 2 3 3]
  [1 2 2 3]
  [1 2 2 3]]

 [[1 1 1 3]
  [1 1 2 3]
  [1 2 2 3]
  [1 1 2 3]]]


In [41]:
print(np.sort(np_4, axis=0))

[[[1 2 1 1]
  [2 1 1 1]
  [2 2 1 1]
  [1 2 2 1]]

 [[2 2 1 2]
  [3 1 1 2]
  [3 2 1 1]
  [1 2 2 1]]

 [[2 3 2 2]
  [3 2 3 2]
  [3 3 2 1]
  [2 2 3 1]]

 [[3 3 2 3]
  [3 2 3 3]
  [3 3 3 2]
  [3 3 3 1]]]


In [43]:
print(np.sort(np_4, axis=1))

[[[2 2 1 1]
  [2 2 2 1]
  [3 3 3 2]
  [3 3 3 2]]

 [[1 1 1 1]
  [2 2 1 1]
  [3 3 2 2]
  [3 3 2 3]]

 [[2 2 1 1]
  [2 2 2 1]
  [3 2 3 2]
  [3 2 3 3]]

 [[1 1 1 1]
  [1 2 1 1]
  [3 2 2 1]
  [3 3 3 2]]]


In [44]:
print(np.sort(np_4, axis=2))

[[[2 2 2 3]
  [1 2 3 3]
  [1 2 3 3]
  [1 2 2 3]]

 [[2 2 2 3]
  [1 1 2 3]
  [1 1 3 3]
  [1 1 2 3]]

 [[1 2 2 3]
  [2 2 3 3]
  [1 2 2 3]
  [1 2 2 3]]

 [[1 1 1 3]
  [1 1 2 3]
  [1 2 2 3]
  [1 1 2 3]]]


In [45]:
np_5 = np.random.randint(1, 5, size=(4, 4))

print(np_5)

[[2 3 1 3]
 [4 4 4 2]
 [2 4 2 2]
 [1 2 2 3]]


In [46]:
np.linalg.det(np_5)

-27.999999999999996

In [50]:
print(np.linalg.inv(np_5))

[[ 0.57142857  0.35714286 -0.57142857 -0.42857143]
 [-0.14285714 -0.21428571  0.64285714 -0.14285714]
 [-0.57142857  0.14285714  0.07142857  0.42857143]
 [ 0.28571429 -0.07142857 -0.28571429  0.28571429]]


In [51]:
print(np.around(np.linalg.inv(np_5), 2))

[[ 0.57  0.36 -0.57 -0.43]
 [-0.14 -0.21  0.64 -0.14]
 [-0.57  0.14  0.07  0.43]
 [ 0.29 -0.07 -0.29  0.29]]


In [53]:
print(np.dot(np_5, np.around(np.linalg.inv(np_5), 2)))

[[ 1.02  0.02 -0.02  0.02]
 [ 0.02  1.02 -0.02  0.02]
 [ 0.02  0.02  0.98  0.02]
 [ 0.02  0.01 -0.02  1.02]]


In [54]:
print(np.around(np.dot(np_5, np.around(np.linalg.inv(np_5), 2)), 0))

[[ 1.  0. -0.  0.]
 [ 0.  1. -0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0. -0.  1.]]


In [55]:
np_6 = np.random.randint(1, 5, size=(4, 4))

print(np_6)

[[1 3 1 3]
 [3 4 3 3]
 [4 2 2 3]
 [3 2 2 1]]


In [57]:
np.split(np_6, 2)

[array([[1, 3, 1, 3],
        [3, 4, 3, 3]]),
 array([[4, 2, 2, 3],
        [3, 2, 2, 1]])]

In [58]:
np.split(np_6, 2, axis=0)

[array([[1, 3, 1, 3],
        [3, 4, 3, 3]]),
 array([[4, 2, 2, 3],
        [3, 2, 2, 1]])]

In [59]:
np.split(np_6, 2, axis=1)

[array([[1, 3],
        [3, 4],
        [4, 2],
        [3, 2]]),
 array([[1, 3],
        [3, 3],
        [2, 3],
        [2, 1]])]

In [60]:
np.hsplit(np_6, 2)

[array([[1, 3],
        [3, 4],
        [4, 2],
        [3, 2]]),
 array([[1, 3],
        [3, 3],
        [2, 3],
        [2, 1]])]

In [61]:
np.vsplit(np_6, 2)

[array([[1, 3, 1, 3],
        [3, 4, 3, 3]]),
 array([[4, 2, 2, 3],
        [3, 2, 2, 1]])]

In [62]:
np.array_split(np_6, 3)

[array([[1, 3, 1, 3],
        [3, 4, 3, 3]]),
 array([[4, 2, 2, 3]]),
 array([[3, 2, 2, 1]])]

In [63]:
np.array_split(np_6, 5)

[array([[1, 3, 1, 3]]),
 array([[3, 4, 3, 3]]),
 array([[4, 2, 2, 3]]),
 array([[3, 2, 2, 1]]),
 array([], shape=(0, 4), dtype=int32)]

In [64]:
np.array_split(np_6, 3, axis=1)

[array([[1, 3],
        [3, 4],
        [4, 2],
        [3, 2]]),
 array([[1],
        [3],
        [2],
        [2]]),
 array([[3],
        [3],
        [3],
        [1]])]

In [65]:
np.array_split(np_6, 5, axis=1)

[array([[1],
        [3],
        [4],
        [3]]),
 array([[3],
        [4],
        [2],
        [2]]),
 array([[1],
        [3],
        [2],
        [2]]),
 array([[3],
        [3],
        [3],
        [1]]),
 array([], shape=(4, 0), dtype=int32)]

In [66]:
np_5 = np.array([1, 2, 3, 4])
np_6 = np.array([5, 4, 2, 1])

In [67]:
print(np.vstack((np_5, np_6)))

[[1 2 3 4]
 [5 4 2 1]]


In [68]:
print(np.hstack((np_5, np_6)))

[1 2 3 4 5 4 2 1]


In [69]:
print(np.concatenate((np_5, np_6)))

[1 2 3 4 5 4 2 1]


In [73]:
print(np.append(np_5, np_6))

[1 2 3 4 5 4 2 1]


In [74]:
np_7 = np.random.randint(1, 5, size=(3, 3))
np_8 = np.random.randint(5, 8, size=(3, 3))

In [75]:
print(np_7)

[[3 4 1]
 [3 4 1]
 [2 1 2]]


In [76]:
print(np_8)

[[6 6 5]
 [7 6 7]
 [5 5 6]]


In [77]:
print(np.vstack((np_7, np_8)))

[[3 4 1]
 [3 4 1]
 [2 1 2]
 [6 6 5]
 [7 6 7]
 [5 5 6]]


In [79]:
print(np.hstack((np_7, np_8)))

[[3 4 1 6 6 5]
 [3 4 1 7 6 7]
 [2 1 2 5 5 6]]


In [81]:
print(np.append(np_7, np_8))

[3 4 1 3 4 1 2 1 2 6 6 5 7 6 7 5 5 6]


In [82]:
print(np.append(np_7, np_8, axis=0))

[[3 4 1]
 [3 4 1]
 [2 1 2]
 [6 6 5]
 [7 6 7]
 [5 5 6]]


In [83]:
print(np.append(np_7, np_8, axis=1))

[[3 4 1 6 6 5]
 [3 4 1 7 6 7]
 [2 1 2 5 5 6]]


In [84]:
np_7 = np.random.randint(1, 5, size=(3, 1))
np_8 = np.random.randint(5, 8, size=(3, 3))

In [85]:
print(np_7)

[[1]
 [3]
 [2]]


In [86]:
print(np_8)

[[6 6 7]
 [7 7 7]
 [7 7 6]]


In [88]:
print(np.hstack((np_7, np_8)))

[[1 6 6 7]
 [3 7 7 7]
 [2 7 7 6]]


In [89]:
np_7 = np.random.randint(1, 5, size=(1, 3))
np_8 = np.random.randint(5, 8, size=(3, 3))

In [90]:
print(np_7)

[[1 4 2]]


In [91]:
print(np_8)

[[5 5 5]
 [6 6 5]
 [7 6 5]]


In [92]:
print(np.vstack((np_7, np_8)))

[[1 4 2]
 [5 5 5]
 [6 6 5]
 [7 6 5]]


In [93]:
np_7 = np.random.randint(1, 5, size=(3, 2))
np_8 = np.random.randint(5, 8, size=3)

In [94]:
print(np_7)

[[3 4]
 [4 1]
 [4 3]]


In [95]:
print(np_8)

[6 5 5]


In [99]:
print(np_8[:, None])

[[6]
 [5]
 [5]]


In [97]:
print(np.hstack((np_7, np_8[:, None])))

[[3 4 6]
 [4 1 5]
 [4 3 5]]


In [101]:
print(np.column_stack((np_7, np_8)))

[[3 4 6]
 [4 1 5]
 [4 3 5]]


In [103]:
print(np.row_stack((np_7.T, np_8)))

[[3 4 4]
 [4 1 3]
 [6 5 5]]


In [116]:
arr = np.arange(5)
np.save('data', arr)

In [117]:
arr = np.arange(5)
np.save('data1.npy', arr)

In [118]:
arr = np.arange(5)
arr1 = np.arange(6, 10)

np.savez('data3', arr, arr1)

In [119]:
np.load('data3.npz')

In [120]:
np.load('data3.npz').files

['arr_0', 'arr_1']

In [121]:
print(np.load('data3.npz')['arr_0'])

[0 1 2 3 4]


In [122]:
print(np.load('data3.npz')['arr_1'])

[6 7 8 9]


In [123]:
arr = np.arange(5)
arr1 = np.arange(6, 10)

np.savez_compressed('data4', arr, arr1)

In [124]:
print(np.load('data1.npy'))

[0 1 2 3 4]


In [125]:
print(np.load('data3.npz'))

In [126]:
arrs = np.load('data3.npz')

In [127]:
arrs

In [128]:
arrs.files

['arr_0', 'arr_1']

In [129]:
print(arrs['arr_0'])

[0 1 2 3 4]


In [130]:
print(arrs['arr_1'])

[6 7 8 9]


In [131]:
arrs_2 = np.load("data4.npz")

In [132]:
arrs_2

In [134]:
arrs_2.files

['arr_0', 'arr_1']

In [135]:
np_1 = np.arange(1, 6)
np_2 = np.arange(6, 10)

np.savez('data5', a=np_1, b=np_2)

In [136]:
arrs_3 = np.load('data5.npz')

In [137]:
arrs_3

In [138]:
arrs_3.files

['a', 'b']

In [139]:
print(arrs_3['a'])

[1 2 3 4 5]


In [140]:
print(arrs_3['b'])

[6 7 8 9]
